apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: meunginx
  serviceName: webserver
  replicas: 2
  template:
    metadata:
      labels:
        app: meunginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx:1.21.3
        ports: 
        - name: webports
          containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:                                            # Chamadas de volumes persistentes
  - metadata:
      name: www
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: standard           # Visto com o comando kubectl get storageclasses -n meupod
      resources:
        requests:
          storage: 1Gi